version: "3"
networks:
    dockerdb:
        external: 
            name: dockerdb
services:
  discovery:
    image: dinezmca/ureka:1.0
    container_name: ureka
    ports:
      - "8761:8761"
    networks:
      - dockerdb