apiVersion: v1
kind: PersistentVolume
metadata:
  name: shop-db-pv-volume
  namespace: shop-development
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/shop"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-db-pv-claim
  namespace: shop-development
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
